premontagem/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add_bike, name="add_bike"),
    path('bike/qr/<str:pk>', views.qr_code_bike, name="qr_code_bike"),
    path('bike/<str:pk>', views.bike_info, name="bike_info"),
]

sangalprototipo1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('premontagem.urls'))
]

premontagem/models.py
from io import BytesIO
from django.db import models


# Create your models here.

class Bike(models.Model):
    LINHA_CHOICES = [
        ('L1', 'Linha 1'),
        ('L2', 'Linha 2'),
    ]

    GEN = [
        ('M', 'M'),
        ('F', 'F'),
    ]

    SIZE = [
        ('44', '44'),
        ('46', '46'),
        ('49', '49'),
        ('53', '53'),
        ('54', '54'),
        ('58', '58'),
    ]

    TRAVAOFRENTE = [
        ('1', 'OK'),
        ('2', 'Desafinado'),
        ('3', 'Não Feito'),
    ]

    TRAVAOTRAS = [
        ('1', 'OK'),
        ('2', 'Desafinado'),
        ('3', 'Não Feito'),
    ]

    MUDANCA = [
        ('1', 'OK'),
        ('2', 'Desafinado'),
        ('3', 'Não Feito'),
    ]


    ordem = models.CharField('Número da Ordem', max_length=50, blank=True)
    marca = models.CharField('Marca', max_length=50, blank=True)
    modelo = models.CharField('Modelo', max_length=50, blank=True)
    genero = models.CharField('Gênero', max_length=2, choices=GEN)
    tamanho = models.CharField('Tamanho', max_length=2, choices=SIZE)
    nquadro = models.CharField('Número do Quadro', max_length=50, blank=True, primary_key=True)
    nmotor = models.CharField('Número do Motor', max_length=50, blank=True)
    ndisplay = models.CharField('Número Display', max_length=50, blank=True)
    ncontrolador = models.CharField('Número do Controlador', max_length=50, blank=True)
    nbateria = models.CharField('Número da Bateria', max_length=50, blank=True)
    linha = models.CharField('Linha de Montagem', max_length=2, choices=LINHA_CHOICES)
    travaofrente = models.CharField('Travão Frente: ', max_length=2, choices=TRAVAOFRENTE)
    travaotras = models.CharField('Travão Tras: ', max_length=2, choices=TRAVAOTRAS)
    mudanca = models.CharField('Mudança: ', max_length=2, choices=MUDANCA)
   # imagem = models.ImageField('Imagem do defeito', null=True)
    descricao = models.TextField('Descrição do defeito', blank=True)

    def __str__(self):
        return str(self.nquadro)

premontagem/forms.py
from django.forms import ModelForm

from premontagem.models import Bike

class AddBicicletaForm(ModelForm):
    class Meta:
        model = Bike
        fields = [
            'ordem',
            'marca',
            'modelo',
            'genero',
            'tamanho',
            'nquadro',
            'nmotor',
            'ndisplay',
            'ncontrolador',
            'nbateria',
            'linha',
            'travaofrente',
            'travaotras',
            'mudanca',
            #'imagem',
            'descricao',

        ]

premontagem/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .forms import AddBicicletaForm
from .models import Bike


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_bikes = Bike.objects.all().count()

    context = {
        'num_bike': num_bikes,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


def add_bike(request):
    form = AddBicicletaForm()
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = AddBicicletaForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('bike_info', args=[form.cleaned_data['nquadro']]))

    context = {
        "form": form
    }
    return render(request, "add_bike.html", context)


def qr_code_bike(request, pk):
    bike = get_object_or_404(Bike, pk=pk)
    context = {"bike": request.build_absolute_uri(reverse('bike_info', args=[bike.nquadro]))}
    return render(request, 'qr_code_bike.html', context)


def bike_info(request, pk):
    bike = get_object_or_404(Bike, pk=pk)
    context = {"bike": bike}
    return render(request, 'info_bike.html', context)

templates/add_bike.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>SANGAL BIKES</h1>
    <h2>Registo de Bicicleta:</h2>
    <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'add_bike' %}">Registar Bicicleta</a></li>
            <li><a href="">Bikes em Premontagem</a></li>
          <li><a href="">Bikes em Linha de Produção 1</a></li>
          <li><a href="">Bikes em Linha de Produção 2</a></li>
          <li><a href="">Bikes em Eletrificação </a></li>
          <li><a href="">Bikes em Qualidade</a></li>
          <li><a href="">Bikes em Reparação</a></li>
          <li><a href="">Bikes em Pintura</a></li>
          <li><a href="">Bikes em Embalamento</a></li>

        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>>

templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>SANGAL BIKES</h1>
  <h2>Sistema de Introdução de Dados</h2>
  <h2>Sistema conta com n registos</h2>
  <p>Sistema conta com registos:</p>
  <ul>
    <li><strong>Bicicletas Registadas:</strong> {{ num_bike }}</li>
  </ul>
{% endblock %}

templates/info_bike.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>SANGAL BIKES</h1>
    <h2>Informações da Bicileta:</h2>
    <p><strong>Número Quadro:</strong><a>{{ bike.nquadro }}</a></p>
    <p><strong>Ordem:</strong> <a href="">{{ bike.ordem }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Marca:</strong> {{ bike.marca }}</p>
    <p><strong>Modelo:</strong> {{ bike.modelo}}</p>
    <p><strong>Número do Display:</strong> {{ bike.ndisplay}}</p>
    <p><strong>Numero do Motor:</strong> {{ bike.nmotor}}</p>
    <p><strong>Linha:</strong> {{ bike.linha}}</p>
    <p><strong>Travão Frente:</strong> {{ bike.get_travaofrente_display}}</p>
    <p><strong>Travão Tras:</strong> {{ bike.get_travaotras_display}}</p>
    <p><strong>Mudança:</strong> {{ bike.get_mudanca_display}}</p>
    <p><a href="{% url 'qr_code_bike' bike.pk %}">Ver QR-CODE</a></p>

{% endblock %}

templates/qr_code_bike.html
{% extends "base_generic.html" %}

{% load qr_code %}

{% block content %}
    {% qr_from_text bike size="10" error_correction='h' %}

{% endblock %}